//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_reply_Tb
    {
        public long reply_id { get; set; }
        public string reply_txt { get; set; }
        public System.DateTime reply_date { get; set; }
        public System.DateTime reply_update { get; set; }
        public int arti_id { get; set; }
        public int user_id { get; set; }
    
        public virtual article_Tb article_Tb { get; set; }
        public virtual user_Tb user_Tb { get; set; }
    }
}
