//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article_Tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public article_Tb()
        {
            this.article_reply_Tb = new HashSet<article_reply_Tb>();
        }
    
        public int arti_id { get; set; }
        public string title { get; set; }
        public System.DateTime arti_date { get; set; }
        public System.DateTime arti_update { get; set; }
        public string arti_txt { get; set; }
        public Nullable<long> view_num { get; set; }
        public Nullable<bool> arti_top { get; set; }
        public Nullable<int> arti_theme { get; set; }
        public int board_id { get; set; }
        public int user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article_reply_Tb> article_reply_Tb { get; set; }
        public virtual board_Tb board_Tb { get; set; }
        public virtual user_Tb user_Tb { get; set; }
    }
}
