//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_Tb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_Tb()
        {
            this.article_reply_Tb = new HashSet<article_reply_Tb>();
            this.article_Tb = new HashSet<article_Tb>();
        }
    
        public int user_id { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string username { get; set; }
        public Nullable<bool> gender { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string account_right { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article_reply_Tb> article_reply_Tb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<article_Tb> article_Tb { get; set; }
    }
}
